version: "3.1"

services:
#  go_service:
#    image: "golang:1.10"
#    build: .
#    env_file:
#      - .env
#    ports:
#      - "${LISTEN_PORT}:8080"
  mysql_service:
    container_name: mysql_service
    image: "mysql:8.0.23"
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
